/* Autogenerated file. Do not edit manually. */

import { TableId } from "@latticexyz/utils";
import { defineComponent, Type as RecsType, World } from "@latticexyz/recs";

export function defineContractComponents(world: World) {
  return {
    Avatar: (() => {
      const tableId = new TableId("", "Avatar");
      return defineComponent(
        world,
        {
          inUsed: RecsType.Boolean,
          owner: RecsType.String,
          url: RecsType.String,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
    Skill: (() => {
      const tableId = new TableId("", "Skill");
      return defineComponent(
        world,
        {
          name: RecsType.String,
          category: RecsType.String,
          atk: RecsType.Number,
          def: RecsType.Number,
          hp: RecsType.Number,
          castTime: RecsType.Number,
          cooldown: RecsType.Number,
          duration: RecsType.Number,
          inUsed: RecsType.Boolean,
          owner: RecsType.String,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
    Account: (() => {
      const tableId = new TableId("", "Account");
      return defineComponent(
        world,
        {
          initialized: RecsType.Boolean,
          avatar: RecsType.String,
          arena: RecsType.String,
          name: RecsType.String,
          skillSet: RecsType.StringArray,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
    Arena: (() => {
      const tableId = new TableId("", "Arena");
      return defineComponent(
        world,
        {
          status: RecsType.String,
          players: RecsType.StringArray,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
    Player: (() => {
      const tableId = new TableId("", "Player");
      return defineComponent(
        world,
        {
          hp: RecsType.Number,
          atk: RecsType.Number,
          def: RecsType.Number,
          nextCasts: RecsType.NumberArray,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
  };
}
