// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Account, AccountData, AccountTableId } from "./tables/Account.sol";
import { Player, PlayerData, PlayerTableId } from "./tables/Player.sol";
import { Skill, SkillData, SkillTableId } from "./tables/Skill.sol";
