// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Avatar, AvatarData, AvatarTableId } from "./tables/Avatar.sol";
import { Skill, SkillData, SkillTableId } from "./tables/Skill.sol";
import { Account, AccountData, AccountTableId } from "./tables/Account.sol";
import { Arena, ArenaData, ArenaTableId } from "./tables/Arena.sol";
import { Player, PlayerData, PlayerTableId } from "./tables/Player.sol";
