// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IAccountSystem {
  function createAccount(string memory name) external;

  function updateName(string memory name) external;

  function setSkills(bytes32[] memory skills) external;
}
