// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IArenaSystem {
  function createArena() external;

  function joinArena(bytes32 id) external;

  function exitArena() external;

  function startBattle() external;
}
