// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { SkillData } from "./../tables/Skill.sol";

interface ISkillSystem {
  function createRandomSkill() external;

  function getSkillProtoType(uint8 index) external pure returns (SkillData memory);
}
